os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
gui:
  nerdFontsVersion: "3"
  showIcons: true
git:
  pagers:
    - colorArg: always
      pager: diff-so-fancy
